"""
Correction Formatter – formats correction data samples for GRPO multitask training.

Correction samples are generated by scripts/mine_correction_data.py and consumed
by training/rl_trainer.py when correction_data_path is configured.

Each sample contains:
  - The original question + schema context
  - The wrong SQL (from the SFT model) + error type + error message
  - The correction reasoning (from teacher LLM) + corrected SQL

In GRPO training, the prompt includes the wrong SQL + error context,
and the model must generate the corrected SQL.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


# ---------------------------------------------------------------------------
# Correction prompt template (must match RetryLoop._build_correction_prompt)
# ---------------------------------------------------------------------------

_CORRECTION_PROMPT_TEMPLATE = """\
Given the schema and question below, the SQL query you previously generated has an error. Fix it.

Schema:
{schema_context}

Question: {question}

Wrong SQL:
```sql
{wrong_sql}
```

Error type: {error_type}
Error message: {error_message}
Hint: {hint}

Generate the corrected SQL inside ```sql ... ```."""

# Error type → hint (mirror of retry_loop._ERROR_HINTS)
_ERROR_HINTS: dict[str, str] = {
    "syntax_error": (
        "The SQL has a syntax error. "
        "Check parentheses, keywords, quotes, and clause ordering."
    ),
    "no_such_table": (
        "A table referenced in the SQL does not exist. "
        "Use only tables listed in the schema above."
    ),
    "no_such_column": (
        "A column referenced in the SQL does not exist. "
        "Check the column names carefully against the schema above."
    ),
    "wrong_result": (
        "The SQL executes but returns incorrect results. "
        "Re-examine the JOIN conditions, WHERE filters, and aggregation logic."
    ),
    "empty_result": (
        "The SQL returns no rows. "
        "Check whether your WHERE conditions are too restrictive "
        "or whether JOINs are eliminating rows unexpectedly."
    ),
    "execution_error": (
        "The SQL caused a runtime error. "
        "Check for type mismatches, division by zero, or unsupported operations."
    ),
}


@dataclass
class CorrectionSample:
    """A single correction training sample.

    Fields
    ------
    question : str
        Original NL question.
    schema_context : str
        Formatted schema string (from SchemaFilter).
    wrong_sql : str
        SQL generated by the SFT model that was incorrect.
    error_type : str
        Error type string (e.g. "syntax_error", "wrong_result").
    error_message : str
        Detailed error message from SQLExecutor.
    corrected_sql : str
        Gold corrected SQL (from teacher LLM or ground-truth).
    correction_reasoning : str
        Reasoning trace explaining the correction (from teacher LLM).
    db_id : str, optional
        Database identifier.
    difficulty : str, optional
        Difficulty label for filtering.
    """

    question: str
    schema_context: str
    wrong_sql: str
    error_type: str
    error_message: str
    corrected_sql: str
    correction_reasoning: str = ""
    db_id: str = ""
    difficulty: str = "unknown"

    def to_grpo_dict(self) -> dict:
        """Convert to GRPO training format.

        Returns
        -------
        dict
            Keys:
              - ``prompt``      : correction prompt (question + schema + wrong SQL + error)
              - ``answer``      : corrected SQL (gold)
              - ``task_type``   : "correction" (used by reward router in rl_trainer.py)
              - ``wrong_sql``   : original wrong SQL (for check_correction_improvement)
              - ``error_type``  : error category string
              - ``error_message``: raw error string
              - ``db_id``       : database identifier
        """
        hint = _ERROR_HINTS.get(self.error_type, "Review the SQL carefully.")
        prompt = _CORRECTION_PROMPT_TEMPLATE.format(
            schema_context=self.schema_context,
            question=self.question,
            wrong_sql=self.wrong_sql,
            error_type=self.error_type,
            error_message=self.error_message or "(no details)",
            hint=hint,
        )
        return {
            "prompt": prompt,
            "answer": self.corrected_sql,
            "task_type": "correction",
            "wrong_sql": self.wrong_sql,
            "error_type": self.error_type,
            "error_message": self.error_message,
            "db_id": self.db_id,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "CorrectionSample":
        """Deserialize from a plain dict (e.g. loaded from JSONL)."""
        return cls(
            question=d["question"],
            schema_context=d.get("schema_context", ""),
            wrong_sql=d["wrong_sql"],
            error_type=d.get("error_type", "execution_error"),
            error_message=d.get("error_message", ""),
            corrected_sql=d.get("corrected_sql", d.get("gold_sql", "")),
            correction_reasoning=d.get("correction_reasoning", ""),
            db_id=d.get("db_id", ""),
            difficulty=d.get("difficulty", "unknown"),
        )

    def to_dict(self) -> dict:
        """Serialize to a plain dict for JSONL storage."""
        return {
            "question": self.question,
            "schema_context": self.schema_context,
            "wrong_sql": self.wrong_sql,
            "error_type": self.error_type,
            "error_message": self.error_message,
            "corrected_sql": self.corrected_sql,
            "correction_reasoning": self.correction_reasoning,
            "db_id": self.db_id,
            "difficulty": self.difficulty,
        }


class CorrectionDataset:
    """Load and serve correction samples for GRPO multitask training."""

    def __init__(self, samples: list[CorrectionSample]):
        self.samples = samples

    @classmethod
    def load(cls, path: str | Path) -> "CorrectionDataset":
        """Load correction samples from a JSONL file."""
        path = Path(path)
        samples: list[CorrectionSample] = []
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                d = json.loads(line)
                samples.append(CorrectionSample.from_dict(d))
        return cls(samples)

    def save(self, path: str | Path) -> None:
        """Save correction samples to a JSONL file."""
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            for sample in self.samples:
                f.write(json.dumps(sample.to_dict(), ensure_ascii=False) + "\n")

    def to_grpo_list(self) -> list[dict]:
        """Convert all samples to GRPO training dicts."""
        return [s.to_grpo_dict() for s in self.samples]

    def filter_by_error_type(self, error_types: list[str]) -> "CorrectionDataset":
        """Return a new dataset filtered to specific error types."""
        filtered = [s for s in self.samples if s.error_type in error_types]
        return CorrectionDataset(filtered)

    def filter_by_difficulty(self, difficulties: list[str]) -> "CorrectionDataset":
        """Return a new dataset filtered to specific difficulty levels."""
        filtered = [s for s in self.samples if s.difficulty in difficulties]
        return CorrectionDataset(filtered)

    def __len__(self) -> int:
        return len(self.samples)

    def __repr__(self) -> str:
        counts: dict[str, int] = {}
        for s in self.samples:
            counts[s.error_type] = counts.get(s.error_type, 0) + 1
        return f"CorrectionDataset(n={len(self.samples)}, error_types={counts})"
